import logging
from google.adk.agents import Agent, SequentialAgent
from google.adk.tools import FunctionTool
from google.cloud import bigquery
from app.tools.taxonomy_tools import semantic_taxonomy_lookup

logger = logging.getLogger("agent")

# =====================================================================
# Sub-Agent 1: DAMSL Dialog Act Annotator
# =====================================================================
ANNOTATOR_PROMPT = """
You are the DAMSL Dialogue Annotator Agent.
Your job is to read a telephone log JSON array of dialogue turns and analyze them one by one.

For each conversational turn, identify and map the Dialogue Act according to the DAMSL/Jurafsky protocol specifications:
- CONVENTIONAL-OPENING: Standard greetings (e.g. "Thank you for calling Cymbal Telecom...", "Hello...")
- CONVENTIONAL-CLOSING: Standard goodbyes (e.g. "Goodbye", "Have a great day...")
- STATEMENT: Conveying facts, details, context, or state parameters
- YES-NO-QUESTION: Yes/No constraints (e.g. "Could you please provide the security PIN?")
- OPEN-QUESTION: Descriptive requests (e.g. "How can I help you today?")
- AGREEMENT: Affirmative validations or concording responses (e.g. "Yes, that's exactly right", "That sounds fine")
- APPRECIATION: Positive emotional feedback (e.g. "Thank you, I appreciate you being so thorough", "That's very efficient")
- BACKCHANNEL: Conversational signaling/acknowledgment cues that do not convey data (e.g. "No problem", "Sure", "No problem, take your time")
- COMMAND: Directives or instructions for action (e.g. "Please check your inbox", "Please take a moment to sign")
- APOLOGY: Regret actions (e.g. "I apologize for that inconvenience")
- THANKING: Conversational expressions of thanks (e.g. "Thank you for taking care of that")
- ACCEPT / REJECT: Confirmations or refusals of options.

Constraint: Output a valid, clean JSON structure representing an array of segments. For each segment, output:
- `timestamp`: Spoken relative timestamp in dialogue turn (e.g. "00:00")
- `speaker`: Spoken role ("Agent" or "User")
- `text`: Word-for-word transcript utterance string.
- `dialogue_act`: Capitalized DAMSL act label from standard list above.
- `abstractive_title`: A brief 3-5 word conceptual heading summarizing the target action/state in this specific turn.

Process the entire dialogue sequence turn-by-turn. Do not skip turns or summarize spans.
"""

damsl_annotator = Agent(
    name="damsl_annotator",
    instruction=ANNOTATOR_PROMPT,
    model="gemini-2.5-pro"
)


# =====================================================================
# Sub-Agent 2: Sequence Clustering Agent
# =====================================================================
CLUSTERING_PROMPT = """
You are the Sequence Clustering Agent.
You will be provided with an array of turn-by-turn dialogue segments generated by damsl_annotator containing dialogue acts and abstractive titles.

Your job is to identify boundaries and group consecutive conversational turns into distinct thematic activity phases or sections of the call.
Common telecom support activity stages include:
- "Opening & Authentication": Greeting, ID request, verification, PIN entries.
- "Problem Discovery": Customer detailing the issue, agent diagnosing account variables.
- "Resolution Processing": Form generation, digital signature cycles, service updates, provisioning.
- "Workaround & Alternative Routing": mergers, conferences, support procedures.
- "Call Closing & Wrap-up": Farewell, summary logs, note entries, ticket linking.

For each identified dialogue section/activity sequence, you must output a structured JSON element matching this schema:
- `sequence_name`: String name representing the target stage (e.g. "Opening & Authentication").
- `est_duration_seconds`: Float duration of this section in seconds (the delta between the earliest turn's timestamp and the timestamp of the first turn in the subsequent section).
- `turns`: Array of chronological dialogue turns grouped under this activity sequence (each turn object must retain timestamp, speaker, text, dialogue_act, and abstractive_title).

CRITICAL POLICY REQUIREMENT: Track and compute ONLY duration metrics (elapsed seconds per activity). Bypassing financial costing operations is standard. Do NOT calculate, estimate, or output any dollar pricing cost values.
"""

sequence_clustering_agent = Agent(
    name="sequence_clustering_agent",
    instruction=CLUSTERING_PROMPT,
    model="gemini-2.5-pro"
)


# =====================================================================
# Sub-Agent 3: High-Reuse Taxonomy Classifier
# =====================================================================
TAXONOMY_PROMPT = """
You are the Taxonomy Classification Agent.
Your job is to read the dialogue segments and clustered sections to determine the call reasons at two structural layers:
- Primary Call Reason: Broad operational domain. Constrained to standard telecom scopes (e.g. Billing, Technical Support, Account Management, Order Management, Payments, Roaming).
- Secondary Call Reason: Granular transactional intent (e.g. Payment Arrangement, Broken Promise, Autopay Failure, Billing Dispute, PIN Reset, Authorized Contact Modification).

To prevent catalog redundancy and optimize taxonomy alignment across standard data models, you MUST execute target lookup tool `{@TOOL: semantic_taxonomy_lookup}` by passing your proposed `primary` and `secondary` call reasons.
The tool will evaluate the parameters against our cloud registry database table using Vector similarity. If the tool identifies a semantic match and returns replacement category names, you MUST override and adopt the returned standard labels to enforce high taxonomy reuse.

CRITICAL FORMAT REQUIREMENT: Your final response must be formatted strictly as a clean, single JSON object block with the following keys and no extra explanations:
```json
{
  "primary_reason": "STRING (e.g. 'Billing')",
  "secondary_reason": "STRING (e.g. 'Missing Payment')"
}
```
"""

taxonomy_classifier = Agent(
    name="taxonomy_classifier",
    instruction=TAXONOMY_PROMPT,
    model="gemini-2.5-pro",
    tools=[FunctionTool(semantic_taxonomy_lookup)]
)


# =====================================================================
# Sub-Agent 4: Data Integration Loader & BQ Insertion Tool
# =====================================================================
DATA_INGESTOR_PROMPT = """
You are the Data Loader Agent.
You will collect:
1. Transcript metadata parameters (call_id, customer_id, customer_name, customer_type, phone, email, services, duration_minutes, total_turns).
2. Annotated turns arrays (from damsl_annotator).
3. Clustered activity sequence sections with duration lists (from sequence_clustering_agent).
4. Confirmed taxonomy reasons (from taxonomy_classifier).

Verify that all payloads are integrated, validate constraints, and construct a single unified payload dictionary strictly matching the following BigQuery table schema structure:

{
  "call_id": "STRING (must exactly match metadata call_id)",
  "customer_id": "STRING (must exactly match metadata customer_id)",
  "customer_name": "STRING or null",
  "customer_type": "STRING or null",
  "phone": "STRING or null",
  "email": "STRING or null",
  "services": "STRING or null",
  "duration_minutes": "INTEGER or null",
  "total_turns": "INTEGER or null",
  "primary_reason": "STRING (must match confirmed taxonomy primary reason)",
  "secondary_reason": "STRING (must match confirmed taxonomy secondary reason)",
  "sequences": [
    {
      "sequence_name": "STRING (name of the section/activity clustered)",
      "est_duration_seconds": "FLOAT (section duration in seconds)",
      "turns": [
        {
          "timestamp": "STRING (relative time e.g. '00:00')",
          "speaker": "STRING ('Agent' or 'User')",
          "text": "STRING (exact spoken text)",
          "dialogue_act": "STRING (DAMSL Act act assigned e.g. 'STATEMENT')",
          "abstractive_title": "STRING (Abstractive title heading assigned)"
        }
      ]
    }
  ]
}

DO NOT use different field names. Ensure that 'sequences' contains fields 'sequence_name' and 'est_duration_seconds' exactly, and under turns, each turn object contains 'timestamp', 'speaker', 'text', 'dialogue_act', and 'abstractive_title' exactly.
Trigger the loading tool `{@TOOL: load_to_bigquery}` passing this formatted target dictionary.
"""

def load_to_bigquery(bq_payload: dict) -> dict:
    """Inserts processed, structured transcripts directly into target BigQuery tables."""
    client = bigquery.Client()
    table_id = "genai-demos-391416.call_analyzer.call_analyzer_table"
    call_id = bq_payload.get("call_id", "UNKNOWN")
    
    try:
        errors = client.insert_rows_json(table_id, [bq_payload])
        if errors:
            logger.error(f"❌ BigQuery Ingestion Failures for {call_id}: {errors}")
            return {"status": "error", "details": str(errors)}
        logger.info(f"✅ Successfully committed call log {call_id} records to BigQuery.")
        return {"status": "success", "message": f"Successfully committed call log {call_id} records to BigQuery."}
    except Exception as e:
        logger.error(f"❌ BigQuery Ingestion Exception for {call_id}: {str(e)}")
        return {"status": "error", "details": str(e)}

data_ingestor = Agent(
    name="data_ingestor",
    instruction=DATA_INGESTOR_PROMPT,
    model="gemini-2.5-flash",
    tools=[FunctionTool(load_to_bigquery)]
)


# =====================================================================
# Root Supervisor Orchestrator Agent
# =====================================================================
ORCHESTRATOR_PROMPT = """
You are the Primary Transcript Orchestrator.
Your goal is to parse telephone transcript archives sequentially and ingest deep dialogue act annotations, structural section sections, and optimized category listings.

Run worker executions sequentially matching strict structural dependencies:
1. Route inputs to `{@AGENT: damsl_annotator}` to map acts and assign abstractive turn headings.
2. Feed outputs to `{@AGENT: sequence_clustering_agent}` to group stages and track elapsed durations.
3. Propagate sequences to `{@AGENT: taxonomy_classifier}` to classify domains and query high-reuse registries.
4. Route final records to `{@AGENT: data_ingestor}` to write structured data to BigQuery analytics engines.

Report back on transaction results showing total elapsed duration, and finalized taxonomic categorizations applied.
"""

root_agent = SequentialAgent(
    name="transcript_orchestrator",
    sub_agents=[damsl_annotator, sequence_clustering_agent, taxonomy_classifier, data_ingestor]
)
